Repository Qovery/terraform-provider-qovery, pull requests merged in 2023-02, with the labels that each got.

#156 feat: Add entrypoint & arguments to application
  docs/data-sources/application.md
  docs/resources/application.md
  examples/resources/qovery_application/resource.tf
  go.mod
  go.sum
  internal/domain/status/status_state.go
  qovery/data_source_application.go
  qovery/resource_application.go
  qovery/resource_application_model.go
  qovery/resource_application_test.go
Labels: enhancement

#164 fix: Fix application deployment
  client/application.go
  client/application_status.go
  qovery/resource_application_model.go
Labels: bug

#167 docs: update supported instance types
  docs/resources/cluster.md
  qovery/data/cluster_instance_types/aws.json
  qovery/data/cluster_instance_types/scaleway.json
  scripts/fetch_instance_types.sh
Labels: documentation

#166 Fix: increase default timeouts
  client/waiter.go
  internal/application/services/deployment_service.go
Labels: bug, enhancement
